- hosts: all
  tasks:
    - name: Ensure i3 config directory exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/i3"
        state: directory
        mode: "0755"

    - name: Install i3 config
      ansible.builtin.copy:
        src: files/i3_config
        dest: "{{ ansible_env.HOME }}/.config/i3/config"
        mode: "0644"

    - name: Install tmux config
      ansible.builtin.copy:
        src: files/tmux.conf
        dest: "{{ ansible_env.HOME }}/.tmux.conf"
        mode: "0644"

    - name: Install vimrc config
      ansible.builtin.copy:
        src: files/vimrc
        dest: "{{ ansible_env.HOME }}/.vimrc
        mode: "0644"
