- name: Install packages
  hosts: localhost
  become: true
  # keep gather facts true. so it will warn if you forgot to prepend w/sudo
  tasks:
    #    - name: Install vim-enhanced
    #      ansible.builtin.dnf:
    #        name: vim-enhanced
    #        state: present
    #        use_backend: dnf4  # or dnf4 depending on your system

    - name: Install vim
      dnf: name=vim-enhanced

    - name: Install tmux
      dnf: name=tmux

    - name: Install emacs
      dnf: name=emacs

    - name: Install gdb
      dnf: name=gdb

    - name: Install gcc
      dnf: name=gcc

    - name: Install valgrind
      dnf: name=valgrind

    #f for f40
    - name: Install gcc-g++
      dnf: name=gcc-g++

    # for rhel9
    - name: Install gcc-c++
      dnf: name=gcc-c++

    # for rhel9
    - name: Install node
      dnf: name=nodejs

    - name: Install npm
      dnf: name=npm

    - name: Install yum-utils
      yum: name=yum-utils

    - name: Install golang
      yum: name=golang

        #    - name: Add ripgrep COPR repository
        #      yum_repository:
        #        name: shassard-ripgrep
        #        description: COPR repo for ripgrep by shassard
        #        file: shassard-ripgrep
        #        baseurl: https://copr.fedorainfracloud.org/coprs/shassard/ripgrep/repo/epel-9/shassard-ripgrep-epel-9.repo
        #        enabled: yes
        #        gpgcheck: no

    - name: Update all packages using yum
      become: true
      yum:
        name: '*'
        state: latest

    - name: Install ripgrep
      yum: name=ripgrep

    # for f40
    - name: Install npm
      dnf: name=nodejs-npm

    # f40 only
    - name: Install tldr globally with npm
      ansible.builtin.command: npm install -g tldr

    - name: Install htop
      dnf: name=htop

    - name: Install fish
      dnf: name=fish

    - name: Install github cli
      dnf: name=gh

    - name: Install Chrome
      dnf: name=google-chrome-stable

#  - name: Set Git global user name
#    ansible.builtin.git_config:
#      name: user.name
#      value: "Eddie Villa"
#      scope: global
#
#  - name: Set Git global user email
#    ansible.builtin.git_config:
#      name: user.email
#      value: "eddie20villa@gmail.com"
#      scope: global
#
#  # GUI only
#  - name: Gnome tweaks
#    dnf: name=gnome-tweaks
