- hosts: localhost
  become: true
  gather_facts: no
  tasks:
  - name: Install htop
    dnf: name=htop

  - name: Install vim
    dnf: name=vim-enhanced

  - name: Install gcc
    dnf: name=gcc

  - name: Install gcc-g++
    dnf: name=gcc-g++

  - name: Install Chrome
    dnf: name=google-chrome-stable

  - name: Install npm
    dnf: name=nodejs-npm

  - name: Install tldr globally with npm
    ansible.builtin.command: npm install -g tldr

#  - name: Set Git global user name
#    ansible.builtin.git_config:
#      name: user.name
#      value: "Eddie Villa"
#      scope: global
#
#  - name: Set Git global user email
#    ansible.builtin.git_config:
#      name: user.email
#      value: "eddie20villa@gmail.com"
#      scope: global
#
