- name: Install packages
  hosts: localhost
  become: true
  # keep gather facts true. so it will warn if you forgot to prepend w/sudo
  tasks:
    - name: Install vim-enhanced
      ansible.builtin.dnf:
        name: vim-enhanced
        state: present
        use_backend: dnf4  # or dnf4 depending on your system

    - name: Install emacs
      dnf: name=emacs

    - name: Install htop
      dnf: name=htop

    - name: Install fish
      dnf: name=fish

    - name: Install gdb
      dnf: name=gdb

    - name: Install gcc
      dnf: name=gcc

    - name: Install valgrind
      dnf: name=valgrind

    - name: Install gcc-g++
      dnf: name=gcc-g++

    - name: Install github cli
      dnf: name=gh

    - name: Install Chrome
      dnf: name=google-chrome-stable

    - name: Install npm
      dnf: name=nodejs-npm

    - name: Install tldr globally with npm
      ansible.builtin.command: npm install -g tldr

#  - name: Set Git global user name
#    ansible.builtin.git_config:
#      name: user.name
#      value: "Eddie Villa"
#      scope: global
#
#  - name: Set Git global user email
#    ansible.builtin.git_config:
#      name: user.email
#      value: "eddie20villa@gmail.com"
#      scope: global
#
